[package]
name = "markhor"
version = "0.1.0"
authors = ["Owen Nelson <onelson@gmail.com>"]
edition = "2021"

[dependencies]
gloo = "0.10.0"
wasm-bindgen = "0.2.88"
yew = { version = "0.21", features = ["csr"] }

