[package]
name = "markhor"
version = "0.1.0"
authors = ["Owen Nelson <onelson@gmail.com>"]
edition = "2021"

[dependencies]
gloo = "0.11.0"
wasm-bindgen = "0.2.88"
web-sys = { version = "0.3.66", features = ["HtmlSelectElement"] }
yew = { version = "0.21", features = ["csr"] }

