
INSERT INTO zones (id, name, description) VALUES
(1, "Dremuchij East", "This is the first area of Snake Eater"),
(2, "Dremuchij North", "The second area of Snake Eater. This area has the very large drop at the beginning, where you cannot return from."),
(3, "Dremuchij Swampland", "This is the area from the Viruous Mission that contains the death trap mud and crocs. You must back track to reach it in the Snake Eater Mission."),
(4, "Dremuchij South", "Just like the swamp, you must back track. This is the area you start in the Viruous mission."),
(5, "Dolinovodno", "The area with the long wooden bridge."),
(6, "Rassvet", "The area where you first fight the GRU, where you meet Ocelot twice, and first recuse Sokolov. Get the Thermals here! This area changes... I couldn't seem to find any birds here during the Snake Eater Mission."),
(7, "Chyornyj Prud", "The larger swamp infrested with fish and crocs."),
(8, "Bolshaya Past South", "The first area with electric fences."),
(9, "Bolshaya Past Base", "The area after the sotuh part with the building and helicopter."),
(10, "Bolshaya Past Crevice", "The fight area against Ocelot."),
(11, "Chyomaya Peschera Cave Branch", "The cave right after the Ocelot fight."),
(12, "Chyomaya Peschera Cave", "The second cave and the area where you fight The Pain."),
(13, "Chyomaya Peschera Cave Entrance", "The area after The Pain fight."),
(14, "Ponizovje South", "This is the long river after the caves."),
(15, "Ponizovje West", "The area west of the long river... this is the first spot you can get the SVD."),
(16, "Ponizovje Warehouse: Exterior", "This is the area before the warehouse, the docks. It is the area where you can kill The End before he gets wheeled in the doors."),
(17, "Ponizovje Warehouse", "Kind of hard to not remember... the Warehouse after the docks."),
(18, "Graniny Gorki South", "The area where you fight The Fear."),
(19, "Graniny Gorki Lab Exterior", "The area outside of the lab, it has an electric fence guarding it."),
(20, "Graniny Gorky Lab 1F", "This is the top floor of the lab."),
(21, "Graniny Gorky Lab B1 East", "The right lower floor of the lab."),
(22, "Svyatogornyj South", "This is the area right after leaving the warehouse though the newly unlocked door."),
(23, "Svyatogornyj West", "This part is right after the South area... not really much else you can say."),
(24, "Svyatogornyj East", "This area is mostly unheard of, as you must keep going right to reach it while in the West."),
(25, "Sokrovenno South", "The first screen during The End fight."),
(26, "Sokrovenno West", "Part of the area you fight The End."),
(27, "Sokrovenno North", "Part of the area you fight The End."),
(28, "Krasnogorje Tunnel", "The area where you fight The Ladder."),
(29, "Krasnogorje Mountain Base", "The first part of the desert mountain. This part has no steep hills yet."),
(30, "Krasnogorje Mountainside", "As the name suggests, this is the area where you will be moving up the mountain."),
(31, "Krasnogorje Mountaintop", "The top of the moutain. This area doesn't have as much climbing, but has trenches."),
(32, "Krasnogorje Mountaintop Ruins", "This is the little shack you meet up with Eva at."),
(33, "Groznyj Grad Underground Tunnel", "This is the whole section where you fight The Fury."),
(34, "Groznyj Grad 1F", "This is the holding cell. All the food from here is given to you if you wait."),
(35, "Groznyj Grad Sewers", "If you didn't know where this was, it is before The Sorrow fight."),
(36, "Tikhogomyj", "The forest area after The Sorrow."),
(37, "Tikhogomyj: Behind Waterfall", "This is the area where you meet up with Eva and get your stuff back."),
(38, "Zaozyorje South", "This is the first part while walking with Eva."),
(39, "Zaozyorje North", "The second part with Eva and the last part of the game without a boss."),
(40, "Rokovoj Bereg", "The Boss fight.")
;
