// id, short_name, name, description, category, collected
pub struct Collectible {
    pub id: usize,
    pub short_name: Option<&'static str>,
    pub name: &'static str,
    pub description: &'static str,
    pub category_id: usize,
}

pub const DATA: [Collectible; 48] = [
    Collectible {
        id: 1,
        short_name: Some("Snake A"),
        name: "King Cobra",
        description: "A large, gray snake.",
        category_id: 1,
    },
    Collectible {
        id: 2,
        short_name: Some("Snake B"),
        name: "Taiwanese Cobra",
        description: "A snake marked with a spectacle pattern.",
        category_id: 1,
    },
    Collectible {
        id: 3,
        short_name: Some("Snake C"),
        name: "Thai Cobra",
        description: "A brown snake.",
        category_id: 1,
    },
    Collectible {
        id: 4,
        short_name: Some("Snake D"),
        name: "Coral Snake",
        description: "A brightly colored snake.",
        category_id: 1,
    },
    Collectible {
        id: 5,
        short_name: Some("Snake E"),
        name: "Milk Snake",
        description: "A brightly colored snake.",
        category_id: 1,
    },
    Collectible {
        id: 6,
        short_name: Some("Snake F"),
        name: "Green Tree Python",
        description: "A large, green snake.",
        category_id: 1,
    },
    Collectible {
        id: 7,
        short_name: Some("Snake G"),
        name: "Giant Anaconda",
        description: "A large snake with black spots.",
        category_id: 1,
    },
    Collectible {
        id: 8,
        short_name: Some("Snake H"),
        name: "Reticulated Python",
        description: "A large snake characterized by a mesh pattern.",
        category_id: 1,
    },
    Collectible {
        id: 9,
        short_name: Some("Snake I"),
        name: "Snake Liquid",
        description: "A mysterious white snake.",
        category_id: 1,
    },
    Collectible {
        id: 10,
        short_name: Some("Snake J"),
        name: "Snake Solid",
        description: "A mysterious white snake.",
        category_id: 1,
    },
    Collectible {
        id: 11,
        short_name: Some("Snake K"),
        name: "Snake Solidus",
        description: "A mysterious white snake.",
        category_id: 1,
    },
    // Mushrooms
    Collectible {
        id: 12,
        short_name: Some("Mushroom A"),
        name: "Russian Oyster",
        description: "A flat-headed mushroom.",
        category_id: 2,
    },
    Collectible {
        id: 13,
        short_name: Some("Mushroom B"),
        name: "Ural Luminescent",
        description: "A mushroom that resembles a shiitake.",
        category_id: 2,
    },
    Collectible {
        id: 14,
        short_name: Some("Mushroom C"),
        name: "Siberian Ink Cap",
        description: "A brown mushroom.",
        category_id: 2,
    },
    Collectible {
        id: 15,
        short_name: Some("Mushroom D"),
        name: "Fly Agaric",
        description: "A red mushroom.",
        category_id: 2,
    },
    Collectible {
        id: 16,
        short_name: Some("Mushroom E"),
        name: "Russian Glow Cap",
        description: "A glowing mushroom.",
        category_id: 2,
    },
    Collectible {
        id: 17,
        short_name: Some("Mushroom F"),
        name: "Spatsa",
        description: "A grey mushroom.",
        category_id: 2,
    },
    Collectible {
        id: 18,
        short_name: Some("Mushroom G"),
        name: "Baikal Scaly Tooth",
        description: "A brown mushroom.",
        category_id: 2,
    },
    // Frogs
    Collectible {
        id: 19,
        short_name: Some("Frog A"),
        name: "Otton Frog",
        description: "A large frog.",
        category_id: 3,
    },
    Collectible {
        id: 20,
        short_name: Some("Frog B"),
        name: "Tree Frog",
        description: "An oddly large tree frog.",
        category_id: 3,
    },
    Collectible {
        id: 21,
        short_name: Some("Frog C"),
        name: "Poison Dart Frog",
        description: "A brightly colored frog.",
        category_id: 3,
    },
    // Birds
    Collectible {
        id: 22,
        short_name: Some("Bird A"),
        name: "Parrot",
        description: "A bird that looks familiar.",
        category_id: 4,
    },
    Collectible {
        id: 23,
        short_name: Some("Bird B"),
        name: "White-Rumped Vulture",
        description: "A large vulture.",
        category_id: 4,
    },
    Collectible {
        id: 24,
        short_name: Some("Bird C"),
        name: "Red Avadavat",
        description: "A small red bird.",
        category_id: 4,
    },
    Collectible {
        id: 25,
        short_name: Some("Bird D"),
        name: "Magpie",
        description: "A bird with a long tail.",
        category_id: 4,
    },
    Collectible {
        id: 26,
        short_name: Some("Bird E"),
        name: "Sunda Whistling Thrush",
        description: "A large black bird.",
        category_id: 4,
    },
    // Fish
    Collectible {
        id: 27,
        short_name: Some("Fish A"),
        name: "Bigeye Trevally",
        description: "A fish with silver eyes.",
        category_id: 5,
    },
    Collectible {
        id: 28,
        short_name: Some("Fish B"),
        name: "Maroon Shark",
        description: "A fish resembling a carp.",
        category_id: 5,
    },
    Collectible {
        id: 29,
        short_name: Some("Fish C"),
        name: "Arowana",
        description: "A large fish.",
        category_id: 5,
    },
    // Fruit
    Collectible {
        id: 30,
        short_name: Some("Fruit A"),
        name: "Yabloko Moloko",
        description: "A red fruit.",
        category_id: 6,
    },
    Collectible {
        id: 31,
        short_name: Some("Fruit B"),
        name: "Russian False Mango",
        description: "A yellow fruit.",
        category_id: 6,
    },
    Collectible {
        id: 32,
        short_name: Some("Fruit C"),
        name: "Golova",
        description: "A large fruit.",
        category_id: 6,
    },
    // Misc
    Collectible {
        id: 33,
        short_name: None,
        name: "Vampire Bat",
        description: "A large bat.",
        category_id: 7,
    },
    Collectible {
        id: 34,
        short_name: None,
        name: "Kenyan Mangrove Crab",
        description: "A large crab.",
        category_id: 7,
    },
    Collectible {
        id: 35,
        short_name: None,
        name: "Indian Gavial",
        description: "A large crocodile.",
        category_id: 7,
    },
    Collectible {
        id: 36,
        short_name: None,
        name: "Markhor",
        description: "A large goat.",
        category_id: 7,
    },
    Collectible {
        id: 37,
        short_name: None,
        name: "Baltic Hornet's Nest",
        description: "A hornet nest.",
        category_id: 7,
    },
    Collectible {
        id: 38,
        short_name: None,
        name: "European Rabbit",
        description: "An ordinary rabbit.",
        category_id: 7,
    },
    Collectible {
        id: 39,
        short_name: None,
        name: "Rat",
        description: "A common rat.",
        category_id: 7,
    },
    Collectible {
        id: 40,
        short_name: None,
        name: "Emperor Scorpion",
        description: "A large scorpion.",
        category_id: 7,
    },
    Collectible {
        id: 41,
        short_name: None,
        name: "Cobalt Blue Tarantula",
        description: "A large spider.",
        category_id: 7,
    },
    Collectible {
        id: 42,
        short_name: None,
        name: "Japanese Flying Squirrel",
        description: "A large flying squirrel.",
        category_id: 7,
    },
    Collectible {
        id: 43,
        short_name: None,
        name: "Tsuchinoko",
        description: "Never seen a snake like this before.",
        category_id: 7,
    },
    Collectible {
        id: 44,
        short_name: None,
        name: "Vine Melon",
        description: "A melon that grows on a vine.",
        category_id: 7,
    },
    // Medi Plants
    Collectible {
        id: 45,
        short_name: None,
        name: "Styptic Plant",
        description: "Effective for treating cuts and gunshot wounds.",
        category_id: 8,
    },
    Collectible {
        id: 46,
        short_name: None,
        name: "Cold Medicine Plant",
        description: "Effective for treating colds.",
        category_id: 8,
    },
    Collectible {
        id: 47,
        short_name: None,
        name: "Disinfectant Plant",
        description: "Effective for treating cuts and gunshot wounds.",
        category_id: 8,
    },
    Collectible {
        id: 48,
        short_name: None,
        name: "Splint Plant",
        description: "Effective for helping broken bones to heal.",
        category_id: 8,
    },
];
